version: '3.2'

services:
  genericy:
    build: .
    image: genericy:latest
    container_name: genericy
    volumes:
      - genericy-data:/genericy
    ports:
      - "8888:8080"
    environment:
      - JAVA_OPTION=-Xmx1024m
    working_dir: /genericy
    restart: unless-stopped

volumes:
  genericy-data:
