version: '3.2'

services:
  genericy:
    image: eclipse-temurin:17-jre-jammy
    container_name: genericy-container
    ports:
      - "8888:8080"
    environment:
      - JAVA_OPTION=-Xmx1024m
    volumes:
      - ./:/genericy
    working_dir: /genericy
    command: >
      bash -c 'if [ ! -e Chinook_Sqlite.sqlite ]; then curl -L -o Chinook_Sqlite.sqlite https://github.com/lerocha/chinook-database/releases/download/v1.4.5/Chinook_Sqlite.sqlite; fi && java -jar genericy.jar'

    # for Linux Systems uncomment the following two lines
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
